version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.33
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466

        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo-db
  mongo-db:
    image: mongo:4.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: axi
      MONGO_INITDB_ROOT_PASSWORD: mysecret42
    ports:
      - '27017:27017'
    volumes:
      - mongo:/var/lib/mongo
volumes: 
  mongo: ~